### ISSUE TITLE
SCM_REVISION变量设置

### ISSUE THREAD

**Issue by imshi** [Statemood/jenkins#1]
你好，请问一下setting文件中SCM_REVISION这个变量在哪里定义（从哪里获取的？）jenkins没有内置该变量...

**Comment by Statemood** [comment]
这个是通过Jenkins参数化构建时利用 Git Parameter 让用户选择的。
是自定义变量，为用户选择的代码Branch or Tag。

**Comment by imshi** [comment]
哦好的，了解，非常谢谢~

**Comment by Statemood** [comment]
不客气
